language: node_js
node_js:
- '8'
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
  - REPO=kpse/web-zft
  - DEPLOY_USER=kpse
  - KEY_PATH=/tmp/deploy_rsa
  - HOST=testzft.cloudenergy.me
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then docker/script/publish.sh v$TRAVIS_BUILD_NUMBER ; fi

before_deploy:
  - openssl aes-256-cbc -K $encrypted_827234cce453_key -iv $encrypted_827234cce453_iv
    -in docker/script/deploy_rsa.enc -out $KEY_PATH -d

addons:
  ssh_known_hosts: testzft.cloudenergy.me

deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 $KEY_PATH && ssh -o StrictHostKeyChecking=no -i $KEY_PATH $DEPLOY_USER@$HOST "./deploy.sh v$TRAVIS_BUILD_NUMBER"
  on:
    branch: develop