language: node_js
node_js:
  - '10'
sudo: required
cache:
  directories:
  - node_modules
env:
  global:
  - REPO=kpse/web-zft
  - DEPLOY_USER=kpse
  - KEY_PATH=/tmp/deploy_rsa
  - HOST=stage.exgcc.com
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then docker/script/publish.sh v$TRAVIS_BUILD_NUMBER;fi
before_deploy:
  - openssl aes-256-cbc -K $encrypted_67ccc51e7df0_key -iv $encrypted_67ccc51e7df0_iv
    -in docker/script/deploy_rsa.enc -out $KEY_PATH -d
  - chmod 600 $KEY_PATH
  - scp -i $KEY_PATH docker/script/deploy.sh $DEPLOY_USER@$HOST:/home/$DEPLOY_USER
  - zip /tmp/dist.zip .blade/dist/**
addons:
  ssh_known_hosts:
    - stage.exgcc.com
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod 600 $KEY_PATH && ssh -o StrictHostKeyChecking=no -i $KEY_PATH $DEPLOY_USER@$HOST
      "./deploy.sh v$TRAVIS_BUILD_NUMBER"
    on:
      branch: master

